all: practice4

practice4: practice4_skeleton.cpp
	g++ -std=c++11 -o practice4 practice4_skeleton.cpp

run: practice4
	./practice4 input3.txt output3.txt
	./practice4 input4.txt output4.txt

clean: practice4
	rm practice4
