all: practice5

practice5: practice5_skeleton.cpp
	g++ -std=c++11 -o practice5 practice5_skeleton.cpp

run: practice5
	./practice5 input7.txt output7.txt
	./practice5 input8.txt output8.txt

clean: practice5
	rm practice5
