all: practice3

practice3: queue_skeleton.cpp
	g++ -std=c++11 -o practice3 queue_skeleton.cpp

run: practice3
	./practice3 queue_input.txt c++_queue_output.txt
	./practice3 stack_input.txt c++_stack_output.txt

clean: practice3
	rm practice3
