all: sorting_skeleton

sorting_skeleton: sorting_skeleton.cpp
	g++ -std=c++11 -o sorting_skeleton sorting_skeleton.cpp

run: sorting_skeleton
	./sorting_skeleton input.txt output.txt

clean: sorting_skeleton
	rm sorting_skeleton
	rm output.txt