all: practice6

practice6: practice6_skeleton.cpp
	g++ -std=c++11 -o practice6 practice6_skeleton.cpp

run: practice6
	./practice6 input5.txt output5.txt
	./practice6 input6.txt output6.txt

clean: practice6
	rm practice6
	rm output5.txt
	rm output6.txt