all: practice7

practice7: practice7_skeleton.cpp
	g++ -std=c++11 -o practice7 most_similar_websites_skeleton.cpp

run: practice7
	./practice7 input5.txt output5.txt
	./practice7 input6.txt output6.txt

clean: practice7
	rm practice7
	rm output5.txt
	rm output6.txt